type Post {
  id: ID
  title: String!
  content: String!
  summary: String
  category: String
  category_id: Int
}

type Query {
  posts(offset: Int, limit: Int): [Post]
  post(id: ID!, offset: Int, limit: Int): Post
  postsByCategory(category_id: Int!, offset: Int, limit: Int): [Post]
  postsByTitle(title: String!, offset: Int, limit: Int): [Post]
}

type Mutation {
  createPost(title: String!, content: String!, summary: String, category_id: Int!): Post
  removePost(id: Int!): Boolean
}

schema {
  query: Query
  mutation: Mutation
}