type Post {
  id: ID
  title: String!
  content: String!
  summary: String
  category: String
  category_id: Int
}

type Query {
  posts: [Post]
}

type Mutation {
  createPost(title: String!, content: String!, summary: String, category_id: Int!): Post
  removePost(id: Int!): Boolean
}

schema {
  query: Query
  mutation: Mutation
}